version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:15.0-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
       - .env
    ports:
      - "5432:5432"
    networks:
      - postgres


  backend:
      container_name: backend
      depends_on:
        - postgres
      build:
        context: .
      env_file:
        - .env
      links:
        - postgres:postgres
      command: ["./entrypoint.bash"]
      volumes:
        - ../scripts/:/opt/scripts/
        - ../debug/:/opt/debug/
        - ../data/:/opt/data/
      expose:
        - "8000"
      networks:
        - postgres 


volumes:
  pgdata:

networks:
  postgres:
    driver: bridge
