# Generated by Django 5.0.6 on 2024-06-15 20:30

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, verbose_name='Тайтлы')),
                ('page_count', models.BigIntegerField(null=True, verbose_name='Количество страниц')),
                ('image', models.CharField(max_length=200, null=True, verbose_name='Обложка')),
                ('status', models.CharField(choices=[('PUBLISH', 'Опубликована'), ('MEAP', 'Предзаказ')], max_length=20, verbose_name='Статус')),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, verbose_name='Авторы'), size=None)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, verbose_name='Категории'), size=None)),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('isbn', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='ISBN')),
                ('short_description', models.TextField(null=True, verbose_name='Короткое описание')),
                ('long_description', models.TextField(null=True, verbose_name='Полное описание')),
                ('subcategories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, verbose_name='Сабкатегории'), blank=True, null=True, size=None)),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'db_table': 'books',
                'get_latest_by': 'pub_date',
                'indexes': [models.Index(fields=['isbn', 'status', 'pub_date'], name='book_main'), models.Index(fields=['isbn', 'status', 'pub_date'], name='book_second')],
            },
        ),
    ]
